version: 0.2
phases:
  install:
    commands:
      - npm ci || npm install
  build:
    commands:
      - npm test
reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: .
